server:
  port: 8100

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: feed-ranker-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.kafka: info
    org.springframework: info
